# Generated by Django 4.2 on 2024-03-22 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('desintext', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('brandlogo', models.ImageField(upload_to='uploads/brands/')),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50, null=True)),
                ('desintext', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('front', models.ImageField(upload_to='uploads/fronts/')),
                ('back', models.ImageField(upload_to='uploads/backs/')),
                ('interior', models.ImageField(upload_to='uploads/interiors/')),
                ('instock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
                ('categoryimage', models.ImageField(upload_to='uploads/categories/')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.IntegerField(default=1)),
                ('customer', models.IntegerField(default=1)),
                ('manager', models.IntegerField(default=1)),
                ('car', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('purpose', models.CharField(max_length=50)),
                ('startdate', models.DateField(default=datetime.datetime.today)),
                ('enddate', models.DateField(default=datetime.datetime.today)),
                ('residence', models.ImageField(upload_to='uploads/contracts/residences/')),
                ('idcard', models.ImageField(upload_to='uploads/contracts/idcards/')),
                ('driverlicense', models.ImageField(upload_to='uploads/contracts/driverlicences/')),
                ('carodometerbefore', models.IntegerField(default=1)),
                ('carsystemstatusbefore', models.TextField(default='Functional')),
                ('carfrontbefore', models.ImageField(upload_to='uploads/contracts/frontstatusbefore/')),
                ('carbackbefore', models.ImageField(upload_to='uploads/contracts/backstatusbefore/')),
                ('carinteriorbefore', models.ImageField(upload_to='uploads/contracts/interiorstatusbefore/')),
                ('cost', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerusername', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerusername', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.IntegerField(default=1)),
                ('customer', models.IntegerField(default=1)),
                ('manager', models.IntegerField(default=1)),
                ('basecost', models.IntegerField(default=0)),
                ('additionalcost', models.IntegerField(default=0)),
                ('totalcost', models.IntegerField(default=0)),
                ('paymentamount', models.IntegerField(default=0)),
                ('change', models.IntegerField(default=0)),
                ('paymentmethod', models.IntegerField(default=1)),
                ('bank', models.IntegerField(default=1)),
                ('account', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(default=1)),
                ('car', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=1)),
                ('purpose', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('startdate', models.DateField(default=datetime.datetime.today)),
                ('enddate', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
