# Generated by Django 4.2 on 2024-03-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='car',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manager',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='manager',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='car',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
