# Generated by Django 4.2 on 2024-04-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_contract_car_alter_contract_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='managerusername',
            new_name='username',
        ),
    ]
