# Generated by Django 4.2 on 2024-04-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_managerusername_manager_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerusername',
            new_name='username',
        ),
    ]
