# Generated by Django 4.2 on 2024-04-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_account_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='request',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
