# Generated by Django 4.2 on 2024-04-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_request_enddate_remove_request_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
