# Generated by Django 4.2 on 2024-04-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='car',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='car',
            field=models.CharField(max_length=255),
        ),
    ]
