# Generated by Django 4.2 on 2024-04-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_contract_car_alter_request_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='additionalcostreason',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
