# Generated by Django 4.2 on 2024-04-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_payment_additionalcostreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='request',
            field=models.CharField(max_length=50),
        ),
    ]
