# Generated by Django 4.2 on 2024-05-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_contract_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='purpose',
            field=models.TextField(max_length=50),
        ),
    ]
