# Generated by Django 4.2 on 2024-07-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_contract_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='createdate_timestamp',
            field=models.CharField(default=1721806664656953.0, max_length=50),
        ),
    ]
