# Generated by Django 4.2 on 2024-08-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_contract_createdate_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='createdate_timestamp',
            field=models.CharField(default='1722482241474654', max_length=50),
        ),
    ]
