# Generated by Django 4.2 on 2024-05-15 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50, null=True)),
                ('desintext', models.TextField(default='No description')),
                ('front', models.ImageField(upload_to='uploads/fronts/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('back', models.ImageField(upload_to='uploads/backs/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('interior', models.ImageField(upload_to='uploads/interiors/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('instock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
