# Generated by Django 4.2 on 2024-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_brand', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('brandname',), name='unique_brand'),
        ),
    ]
