# Generated by Django 4.2 on 2024-05-15 04:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('car', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('purpose', models.TextField(max_length=50)),
                ('startdate', models.DateField(default=datetime.datetime.today)),
                ('enddate', models.DateField(default=datetime.datetime.today)),
                ('residence', models.ImageField(upload_to='uploads/contracts/residences/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('idcard', models.ImageField(upload_to='uploads/contracts/idcards/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('driverlicense', models.ImageField(upload_to='uploads/contracts/driverlicences/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('carodometerbefore', models.IntegerField(default=1)),
                ('carsystemstatusbefore', models.TextField(default='Functional')),
                ('carfrontbefore', models.ImageField(upload_to='uploads/contracts/frontstatusbefore/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('carbackbefore', models.ImageField(upload_to='uploads/contracts/backstatusbefore/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('carinteriorbefore', models.ImageField(upload_to='uploads/contracts/interiorstatusbefore/', validators=[django.core.validators.FileExtensionValidator(['apng', 'png', 'gif', 'svg', 'ico', 'cur', 'jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp', 'webp'])])),
                ('cost', models.IntegerField(default=0)),
                ('createdate', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
